blog/account/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import register, profile_detail, edit_profile_view 


urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(template_name='account/login.html'),
        name='login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='account/loggedout.html'),
        name="logout"
    ),

    path('registration/', register, name='register'),

    path('profile/<int:profile_id>/', profile_detail, name='profile_detail'),

    path(
        'profile-edit/<int:profile_id>',
        edit_profile_view,
        name='profile_edit'
    )
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', include('posts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "posts.views.handle_page_not_found"

blog/posts/urls.py
from django.urls import path
from .views import (
    PostCreateApiView,
    PostsHome,
    PostDetail,
    PostCreationView,
)



urlpatterns = [
    path('', PostsHome.as_view(), name='home'),
    path(
        '<slug:post_slug>',
        PostDetail.as_view(),
        name='post_detail'
    ),
    path(
        'create/',
        PostCreationView.as_view(),
        name='post_create'
    ),
    path(
        'api/v1/post_list/', PostCreateApiView.as_view()
    )
]

blog/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Автор",
        related_name="posts",
    )
    title = models.CharField(verbose_name="Заголовок", max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    body = models.TextField(verbose_name="Контент")
    published = models.DateTimeField(
        verbose_name="Дата и время публикации",
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        verbose_name="Дата и время последнего изменения",
        auto_now=True,
    )
    rating = models.IntegerField(
        verbose_name='Рейтинг',
        default=0
    )
    # rated_by??? = [???]

    class Meta:
        ordering = ['-published']

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'post_slug': self.slug})


class Comment(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    name = models.CharField(max_length=150)

    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self) -> str:
        return f'Комментарий {self.name} к посту {self.post}'

blog/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')

    def clean_title(self):
        title = self.cleaned_data['title']
        try:
            Post.objects.get(slug=slugify(title))
        except Exception:
            return title
        else:
            raise ValidationError('Пост с таким заголовком уже опубликован.')

blog/posts/views.py
import time
from django.http import HttpRequest
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import FormMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify

from django.forms import ModelForm, model_to_dict
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.request import Request
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import (
    CreateAPIView,
    RetrieveUpdateDestroyAPIView,
    ListCreateAPIView,
)
from rest_framework import permissions

from .serializers import PostSerializer

from .models import Post
from .forms import CommentForm, PostForm
from .permissions import IsOwnerOrReadOnly


class PostsHome(ListView):
    paginate_by = 5
    model = Post
    context_object_name = "posts"
    template_name = "posts/home.html"

    def get_queryset(self):
        return Post.objects.all()


class PostDetail(FormMixin, DetailView):
    model = Post
    template_name = "posts/post.html"
    context_object_name = "post"
    slug_url_kwarg = "post_slug"
    form_class = CommentForm

    def get_success_url(self) -> str:
        return reverse("post_detail", kwargs={"post_slug": self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = context["post"].comments.all()
        print(context["comments"])
        context["form"] = CommentForm()
        return context

    def post(self, request: HttpRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("account:login", permanent=True)

        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form, request.user.username)
        else:
            return self.form_invalid(form)

    def form_valid(self, form: ModelForm, username):
        comment = form.save(commit=False)
        comment.name = username
        comment.post = self.object
        comment.save()
        return super(PostDetail, self).form_valid(comment)


class PostCreationView(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = "posts/post_create_form.html"

    def form_valid(self, form):
        post = form.save(commit=False)
        post.slug = slugify(self.request.POST["title"])
        post.author = self.request.user
        post.save()
        return super(PostCreationView, self).form_valid(form)


# class PostAPIView(APIView):
#     def get(self, request):
#         lst = Post.objects.all()
#         return Response({'posts': PostSerializer(lst, many=True).data})

#     def post(self, request: Request):
#         print(type(request.user))

#         serializer = PostSerializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()

#         return Response({'message': serializer.data})

#     def patch(self, requser, *args, **kwargs):
#         return Response({"message": "PATCH request"})


# class PostViewSet(ModelViewSet):
#     queryset = Post.objects.all()
#     serializer_class = PostSerializer


class PostCreateApiView(ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class PostDetailApiView(RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = (IsOwnerOrReadOnly,)


def handle_page_not_found(request, *args, **argv):
    return render(request, "posts/404.html", context={})

blog/posts/templates/posts/base.html
{% load static %}
{% load bootstrap5 %}
{% load blog_app_tags %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "posts/css/styles.css" %}">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<body>
    <header class="p-3" style="background-color: #212529;">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'home' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><rect width="40px" height="32px" fill="white"/>
                <text x="4" y="23" font-family="Verdana" font-size="20" fill="#212529" stroke-width="2">MD
                </text></svg>
            </a>
    
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="{% url 'home' %}" class="nav-link px-2 bl-hover selected">Home</a></li>
              {% if request.user.is_authenticated %} 
                <li><a href="{% url 'account:profile_edit' request.user.id %}" class="nav-link px-2 bl-hover">Edit profile</a></li> 
              {% endif %}
            </ul>
            <div class="text-end">
              {% if request.user.is_authenticated %}
              <a class="text-link btn user-profile" href="{% url 'account:profile_detail' request.user.id %}">{{ request.user.username }}</a>
                <a href="{% url 'account:logout' %}"><button type="button" class="btn btn-outline-light me-2">Logout</button></a>
              {% else %}
                <a href="{% url 'account:login' %}"><button type="button" class="btn btn-outline-light  me-2">Login</button></a>
                <a href="{% url 'account:register' %}"<button type="button" class="btn sign-up">Sign-up</button></a>
              {% endif %}
            </div>
          </div>
        </div>
      </header>
      <div class="content">
        {% block content %}
        {% endblock content %}
      </div>
</body>
</html>

blog/posts/templates/posts/home.html
{% extends 'posts/base.html' %}
{% load static %}
{% block title %}Блог{% endblock title %}
{% block content %}
<div class="home-page-wrapper infinite-container">
    {% if request.user.is_authenticated %}
    <a class="width-100 margin-bott-10px" href="{% url 'post_create' %}"><button class="new-post width-100">+ Создать
            новый пост</button></a>
    {% endif %}

    {% for p in posts %}
    <div class="infinite-item">
        <div class="element">
            <a class="text-link" href="{{ p.get_absolute_url }}">
                <h3 class="overflow">{{ p.title }}</h3>
            </a>
        </div>
        <span class="creation-date element">{{ p.published }}</span>

        <div class="post-author-rating element">
            <span class="author overflow">Автор: {{ p.author.username }}</span>
            {% with p.rating as rate %}
            <span class="rating 
                        {% if rate > 0 %}
                            good
                        {% else %}
                            bad
                        {% endif %}
                    ">★ {{ rate }}</span>
            {% endwith %}

        </div>
        <div class="post-body element">
            <span class="post-text">{{ p.body|truncatewords:50 }}</span>
        </div>
        <span class="last-modified-date element">Последнее изменение: {{ p.modified }}</span>

    </div>
    {% endfor %}
</div>

<script src="{% static 'posts/js/jquery.waypoints.min.js' %}"></script>
<script src="/static/posts/js/infinite.min.js"></script>

<script>
    const container = document.querySelector('.infinite-container');

    var next_page_number = {{ page_obj.next_page_number }}
    function load_pages(numImages = 10) {
        $.ajax({
            url: `{% url 'home' %}?page=${next_page_number}`,
            type: "GET",
            dataType: "html",
            success: function (data) {
                var cont = $($.parseHTML(data)).find(".infinite-item")
                container.appendChild
                cont.each(function(){
                    container.appendChild(this)
                })
                next_page_number++;
            }
        })
    }

    window.addEventListener('scroll', () => {
        if (window.scrollY + window.innerHeight >= document.documentElement.scrollHeight) {
            load_pages();
        }
    })
</script>
{% endblock content %}

blog/posts/templates/posts/post.html
{% extends 'posts/base.html' %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
    <div class="post-detail-wrapper">
        <div class="post-header">
            <h1 class="overflow">{{ post }}</h1>
                {% with post.rating as rate %}
                    <span class="post-rating 
                        {% if rate > 0 %}
                            good
                        {% else %}
                            bad
                        {% endif %}
                    ">★ {{ rate }}</span>
                {% endwith %}
        </div>
        <line></line>
        <div class="dates">
            <div class="published">Опубликовано: {{ post.published }}</div>
            <div class="modified last-modified-date">Последняя модификация: {{ post.modified }}</div>
        </div>

        <div class="author-post">
            Автор: <a class="text-link" href="{% url 'account:profile_detail' post.author.id %}">{{ post.author }}</a>
        </div>

        <div class="post-body">
            {{ post.body }}
        </div>

        {% if request.user.is_authenticated %}
            <form class="comment-form" action="./{{ post.slug }}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="{{ field.label }}">
                        <div class="avatar-plug-form">
                            <svg height="2rem" width="2rem">
                                <circle cx="1rem" cy="1rem" r="1rem" fill="#2e82ff"/>
                            </svg>
                        </div>
                        {{ field }} 
                        <div class="error">{{ field.errors }}</div> 
                    </div>
                {% endfor %}
                <button class="comment-form-button" type="submit">Оставить комментарий</button>
            </form>
        {% else %}
            <span class="login-required">Чтобы оставить комментарий, пожалуйста, авторизуйтесь.</span>
            <line></line>
        {% endif %}
        
        <div class="comments">
            <ul class="comments-list">
                {% for comment in comments %}
                    <li class="comment">
                        <div class="avatar-plug">
                            <svg height="2rem" width="2rem">
                                <circle cx="1rem" cy="1rem" r="1rem" fill="#2e82ff"/>
                            </svg>
                        </div>
                        <div class="comment-body">
                            <strong>{{ comment.name }}</strong>
                            <span class="comment-date">{{ comment.created }}</span>
                            <div class="comment-text">{{ comment.body }}</div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

blog/posts/templates/posts/post_create_form.html
{% extends 'posts/base.html' %}
{% block title %}Новый пост{% endblock title %}
{% block content %}
    <div class="post-creation-wrapper">
        <form class="post-create-form" action="." method="post">
            {% csrf_token %} 
            {% for field in form  %}
                <div class="{{ field.name }}-post-create">
                    {{ field.label }}:
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <button class="comment-form-button" type="submit">Опубликовать</button>
        </form>
    </div>
{% endblock content %}

blog/posts/templates/posts/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=p, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{ penis }}</p>
    <script>alert( document.cookie );</script>
</body>
</html>